apiVersion: apps/v1
kind: Deployment
metadata:
  name: eorkwm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eorkwm
  template:
    metadata:
      labels:
        app: eorkwm
    spec:
      containers:
      - image: okteto.dev/eorkwm:latest
        name: eorkwm
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "56956827-9c9c-4e0b-9ff2-98abd4160d6a"
        - name: Vless_Path
          value: "/56956827-9c9c-4e0b-9ff2-98abd4160d6a"
        - name: Vmess_UUID
          value: "d398eebe-3c19-4105-a335-54ab1028af03"
        - name: Vmess_Path
          value: "/d398eebe-3c19-4105-a335-54ab1028af03"
        - name: Share_Path
          value: "/Share204"
